// flow-typed signature: fb8c47dc74f8cc0847fda71004265715
// flow-typed version: <<STUB>>/form-data-to-object_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'form-data-to-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'form-data-to-object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'form-data-to-object/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'form-data-to-object/index' {
  declare module.exports: $Exports<'form-data-to-object'>;
}
declare module 'form-data-to-object/index.js' {
  declare module.exports: $Exports<'form-data-to-object'>;
}
declare module 'form-data-to-object/test.js' {
  declare module.exports: $Exports<'form-data-to-object/test'>;
}
