// flow-typed signature: 06b007a5ace13b7c625e1cd6eed14b5a
// flow-typed version: <<STUB>>/keycode_v^2.1.7/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keycode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keycode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keycode/test/keycode' {
  declare module.exports: any;
}

declare module 'keycode/test/mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keycode/index' {
  declare module.exports: $Exports<'keycode'>;
}
declare module 'keycode/index.js' {
  declare module.exports: $Exports<'keycode'>;
}
declare module 'keycode/test/keycode.js' {
  declare module.exports: $Exports<'keycode/test/keycode'>;
}
declare module 'keycode/test/mocha.js' {
  declare module.exports: $Exports<'keycode/test/mocha'>;
}
