// flow-typed signature: 1bc325ab7b68141f46f2250a8b04f68c
// flow-typed version: <<STUB>>/tippy.js_v^1.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tippy.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tippy.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tippy.js/dist/tippy' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.min' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.standalone' {
  declare module.exports: any;
}

declare module 'tippy.js/main' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/bindEventListeners' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/createPopperElement' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/createPopperInstance' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/createTooltips' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/createTrigger' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/followCursorHandler' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/getArrayOfElements' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/getEventListenerHandlers' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/getIndividualSettings' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/globals' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/hideAllPoppers' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/init' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/makeSticky' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/mountPopper' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/core/onTransitionEnd' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/tippy' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/applyTransitionDuration' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/closest' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/cursorIsOutsideInteractiveBorder' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/elementIsInViewport' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/find' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/findIndex' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/getCorePlacement' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/getOffsetDistanceInPx' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/isVisible' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/matches' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/modifyClassList' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/noop' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/prefix' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/queueExecution' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/removeTitle' {
  declare module.exports: any;
}

declare module 'tippy.js/src/js/utils/triggerReflow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tippy.js/dist/tippy.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy'>;
}
declare module 'tippy.js/dist/tippy.min.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.min'>;
}
declare module 'tippy.js/dist/tippy.standalone.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.standalone'>;
}
declare module 'tippy.js/main.js' {
  declare module.exports: $Exports<'tippy.js/main'>;
}
declare module 'tippy.js/src/js/core/bindEventListeners.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/bindEventListeners'>;
}
declare module 'tippy.js/src/js/core/createPopperElement.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/createPopperElement'>;
}
declare module 'tippy.js/src/js/core/createPopperInstance.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/createPopperInstance'>;
}
declare module 'tippy.js/src/js/core/createTooltips.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/createTooltips'>;
}
declare module 'tippy.js/src/js/core/createTrigger.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/createTrigger'>;
}
declare module 'tippy.js/src/js/core/followCursorHandler.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/followCursorHandler'>;
}
declare module 'tippy.js/src/js/core/getArrayOfElements.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/getArrayOfElements'>;
}
declare module 'tippy.js/src/js/core/getEventListenerHandlers.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/getEventListenerHandlers'>;
}
declare module 'tippy.js/src/js/core/getIndividualSettings.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/getIndividualSettings'>;
}
declare module 'tippy.js/src/js/core/globals.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/globals'>;
}
declare module 'tippy.js/src/js/core/hideAllPoppers.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/hideAllPoppers'>;
}
declare module 'tippy.js/src/js/core/init.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/init'>;
}
declare module 'tippy.js/src/js/core/makeSticky.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/makeSticky'>;
}
declare module 'tippy.js/src/js/core/mountPopper.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/mountPopper'>;
}
declare module 'tippy.js/src/js/core/onTransitionEnd.js' {
  declare module.exports: $Exports<'tippy.js/src/js/core/onTransitionEnd'>;
}
declare module 'tippy.js/src/js/tippy.js' {
  declare module.exports: $Exports<'tippy.js/src/js/tippy'>;
}
declare module 'tippy.js/src/js/utils/applyTransitionDuration.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/applyTransitionDuration'>;
}
declare module 'tippy.js/src/js/utils/closest.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/closest'>;
}
declare module 'tippy.js/src/js/utils/cursorIsOutsideInteractiveBorder.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/cursorIsOutsideInteractiveBorder'>;
}
declare module 'tippy.js/src/js/utils/elementIsInViewport.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/elementIsInViewport'>;
}
declare module 'tippy.js/src/js/utils/find.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/find'>;
}
declare module 'tippy.js/src/js/utils/findIndex.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/findIndex'>;
}
declare module 'tippy.js/src/js/utils/getCorePlacement.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/getCorePlacement'>;
}
declare module 'tippy.js/src/js/utils/getOffsetDistanceInPx.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/getOffsetDistanceInPx'>;
}
declare module 'tippy.js/src/js/utils/isVisible.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/isVisible'>;
}
declare module 'tippy.js/src/js/utils/matches.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/matches'>;
}
declare module 'tippy.js/src/js/utils/modifyClassList.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/modifyClassList'>;
}
declare module 'tippy.js/src/js/utils/noop.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/noop'>;
}
declare module 'tippy.js/src/js/utils/prefix.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/prefix'>;
}
declare module 'tippy.js/src/js/utils/queueExecution.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/queueExecution'>;
}
declare module 'tippy.js/src/js/utils/removeTitle.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/removeTitle'>;
}
declare module 'tippy.js/src/js/utils/triggerReflow.js' {
  declare module.exports: $Exports<'tippy.js/src/js/utils/triggerReflow'>;
}
