// @flow
import omit from 'lodash/omit'

// Removes component props that shouldn't be set on the form control.
export default (props: Object) =>
  omit(props, [
    'addonAfter',
    'addonBefore',
    'buttonAfter',
    'buttonBefore',
    'classNames',
    'elementWrapperClassName',
    'externalError',
    'formControl',
    'formSubmitted',
    'getErrorMessage',
    'getErrorMessages',
    'getValue',
    'hasValue',
    'help',
    'inline',
    'isFormDisabled',
    'isFormSubmitted',
    'isPristine',
    'isPristine',
    'isRequired',
    'isRequired',
    'isValid',
    'isValid',
    'isValidValue',
    'label',
    'labelClassName',
    'layout',
    'mapping',
    'onChange',
    'onError',
    'onInvalid',
    'onInvalidSubmit',
    'onSubmit',
    'onSuccess',
    'onValid',
    'onValidSubmit',
    'options',
    'preventExternalInvalidation',
    'pristineValue',
    'reset',
    'resetValue',
    'rowClassName',
    'rowLabel',
    'setValidations',
    'setValue',
    'showError',
    'showRequired',
    'tagGroup',
    'validatePristine',
    'validation',
    'validationError',
    'validationError',
    'validationErrors'
  ])
